# Wave 0: NVIDIA Device Plugin
# Enables Kubernetes GPU scheduling by exposing nvidia.com/gpu resources.
# Must tolerate the GPU node taint (nvidia.com/gpu:NoSchedule) to run on GPU nodes.
# Runs in parallel with Istio components (wave 0).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.17.0
    helm:
      releaseName: nvidia-device-plugin
      values: |
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
          - key: CriticalAddonsOnly
            operator: Exists
            effect: NoSchedule
        nodeSelector:
          kubernetes.io/os: linux
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
